# Generated by Django 4.1.6 on 2023-02-12 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_friends_profile_friends_friend_friends_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='user',
            new_name='profile',
        ),
    ]
