# Generated by Django 4.1.6 on 2023-02-14 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_friends_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='profile',
        ),
    ]
