# Generated by Django 4.1.6 on 2023-02-14 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_friends_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to='client.profile'),
            preserve_default=False,
        ),
    ]
