# Generated by Django 4.1.6 on 2023-02-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_friends_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
