# Generated by Django 4.1.6 on 2023-02-14 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_friends_friendrequests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequests',
        ),
    ]
