# Generated by Django 4.1.6 on 2023-02-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_friends_id_alter_friends_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='websocket_user_channel',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
