# Generated by Django 4.1.6 on 2023-02-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_profile_bio_profile_profile_pic_profile_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
