# Generated by Django 4.1.6 on 2023-02-25 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgn', models.CharField(blank=True, max_length=4000, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='result', to='client.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('websocket_channel', models.CharField(blank=True, max_length=256, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client.profile')),
            ],
            options={
                'unique_together': {('game', 'player')},
            },
        ),
    ]
