# Generated by Django 4.1.6 on 2023-02-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_alter_playergamelink_unique_together_game_black_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='websocket_game_channel',
        ),
        migrations.AddField(
            model_name='playergamelink',
            name='websocket_game_channel',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
