# Generated by Django 4.1.6 on 2023-02-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_remove_profile_websocket_game_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='next_mode',
            field=models.CharField(default='white', max_length=32),
        ),
    ]
