# Generated by Django 4.1.6 on 2023-02-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_game_next_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pgn_headers',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='pgn',
            field=models.CharField(default='1.', max_length=4000),
        ),
    ]
