# Generated by Django 4.1.6 on 2023-02-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_game_pgn_headers_alter_game_pgn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='next_mode',
            new_name='next_move',
        ),
    ]
