# Generated by Django 4.1.6 on 2023-03-02 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_statuscomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statuscomment',
            name='commenter',
        ),
        migrations.RemoveField(
            model_name='statuscomment',
            name='status',
        ),
    ]
