# Generated by Django 4.1.6 on 2023-03-02 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_remove_statuscomment_commenter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCommentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client.statuscomment')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client.profile')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client.status')),
            ],
        ),
        migrations.AddField(
            model_name='status',
            name='comments',
            field=models.ManyToManyField(through='client.StatusCommentLink', to='client.statuscomment'),
        ),
    ]
